### ISSUE TITLE
Methods other than sendMessage do not accept chat_id

### ISSUE THREAD

**Issue by Akaiyo** [rainu/telegram-bot-api#1]
When I try to call bot.sendAudio or bot,sendPhoto I get a "Bad Request: chat_id is empty " despite using the same chatID as in sendMessage (which works perfectly fine)

**Comment by ValeriyMaslenikov** [comment]
+1
Problem really exists, please, fix it :(

**Comment by rainu** [comment]
Thank you for reporting this issue (sorry about my late answer - i don't saw it -.-)

I think the telegram-developer have changed there API. However, i fixed that issue. Now you don't get this exception anymore. But if you send an audio file you will get a BotException ("Could not deserialize response!") - because the response body [has been changed](https://core.telegram.org/bots/api-changelog#august-15-2015). But the audio-message will be sent.

I will make a [litte fix-release](https://repo1.maven.org/maven2/de/raysha/lib/telegram/bot-api/1.0.1/). But i think i should check all api-calls against the update [telegram-bot-api](https://core.telegram.org/bots/api-changelog) :)

**Comment by armsepehr** [comment]
The problem still exists in forwardMessage. I am using same chat_id for both forwardMessage and sendMessage; however it gives me "Bad Request: chat_id is empty" in forwardMessage.
